-- Таблица "Orders"
ALTER TABLE Orders
ALTER COLUMN ClientID SET NOT NULL,
ALTER COLUMN VegetableID SET NOT NULL,
ALTER COLUMN Quantity SET NOT NULL,
ALTER COLUMN OrderDate SET NOT NULL,
ALTER COLUMN TotalPrice SET NOT NULL
ADD CONSTRAINT chk_quantity CHECK (Quantity > 0),
ADD CONSTRAINT chk_total_price CHECK (TotalPrice >= 0),
ADD CONSTRAINT fk_client FOREIGN KEY (ClientID) REFERENCES Clients(ID) ON DELETE CASCADE,
ADD CONSTRAINT fk_vegetable FOREIGN KEY (VegetableID) REFERENCES Vegetables(ID) ON DELETE CASCADE;
